name = "PowerNumbers"
uuid = "7635a310-babe-11e9-2fde-a3dff3ddcf26"
authors = ["idlemat <52246739+idlemat@users.noreply.github.com>"]
version = "0.1.0"

[deps]
DualNumbers = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"

[targets]
test = ["Test","HypergeometricFunctions"]
